// Anno 117 game data, generated by scripts/extract-117.mjs from
// anno-mods/anno-117-calculator (see data-117.json `source` for the pinned
// commit). Regenerate with `npm run extract:117`; don't hand-edit the JSON.
// The 1800 counterpart is data.ts — this mirrors its shape so the two packs
// read the same way, with the differences called out below.
import raw from "./data-117.json";

/** [id, name, regionMask, tier, building, cycleTime, "input|input"] */
export type GoodTuple117 = [string, string, number, string, string | null, number, string];

/** [tons/min per resident, category band 0..3 (see CAT_LABELS_117)] */
export type NeedDef117 = [number, number];

/** One way to make a good. A good can have several: the same building in both
 *  regions, a different building per region (Flour: Grain Mill in Latium,
 *  Donkey Mill in Albion), different inputs per region (Leather, Amphorae,
 *  Tiles), or a same-region choice (Coal: Charcoal Burner or Coal Mine). */
export interface Producer117 {
  building: string;
  time: number;
  inputs: string;
  /** Bitmask of the regions this producer exists in. */
  region: number;
  /** Burns FUEL117.good on top of its inputs. */
  fuel?: boolean;
  /** Max module SLOTS this building takes — a farm's fields are modules too,
   *  which is why these run to 80/140/180. A Silo occupies slots like any
   *  other module; this is NOT a count of silos. */
  modulesLimit?: number;
  /** Needs this island fertility/deposit to be placeable. */
  fertility?: string | boolean;
}

export interface PopTier117 {
  lbl: string;
  /** 1 Latium or 2 Albion — a tier belongs to exactly one region. */
  region: number;
  workforceFactor: number | null;
  workforce: number | null;
  n: Record<string, NeedDef117>;
  /** Public-service buildings the tier needs: [name, category band]. */
  services: [string, number][];
}

export interface Good117 {
  id: string;
  name: string;
  /** Bitmask, NOT a single region id like data.ts: 1 Latium, 2 Albion, 3 both. */
  region: number;
  regionNames: string[];
  tier: string | null;
  tierName: string | null;
  /** The primary producer's building — null for a gathered good. */
  building: string | null;
  time: number;
  /** t/min per building at base productivity. 0 for a gathered good. */
  rate: number;
  inputs: { good: string; qty: number }[];
  isFinal: boolean;
  /** Every way to make it, primary first. Empty when gathered. */
  producers: Producer117[];
  /** Comes from an island deposit, not a building (Obsidian). */
  gathered: boolean;
}

interface RawData117 {
  _C: {
    version: string;
    game: string;
    g: GoodTuple117[];
    alts: Record<string, never>;
    POP: Record<string, PopTier117>;
    tierOrder: Record<string, number>;
    tierLabels: Record<string, string>;
    regions: Record<string, string>;
    catLabels: string[];
  };
  producers: Record<string, Producer117[]>;
  gathered: string[];
  fuel: { good: string | null; time: number };
  silo: { feedGood: string | null; feedPerMin: number | null; productivityUpgrade: number | null };
  presets: { name: string; sel: Record<string, [string, number]> }[];
  source: Record<string, string>;
}

const data = raw as unknown as RawData117;
const _C = data._C;

export const VERSION_117 = _C.version;
export const SOURCE_117 = data.source;
export const REGIONS_117: Record<number, string> = Object.fromEntries(
  Object.entries(_C.regions).map(([k, v]) => [Number(k), v])
);
export const TIER_ORDER_117 = _C.tierOrder;
export const TIER_LABELS_117 = _C.tierLabels;
export const POP_117 = _C.POP;
export const CAT_LABELS_117 = _C.catLabels;
export const PRESETS_117 = data.presets;

/** Buildings that burn fuel consume one unit of `good` per `time` seconds, so a
 *  building on a `cycleTime` loop burns cycleTime/time each cycle. */
export const FUEL_117 = data.fuel;
/** The Silo module: eats `feedPerMin` t/min of `feedGood` and raises output. */
export const SILO_117 = data.silo;

const gatheredSet = new Set(data.gathered);

export const GOODS_117: Record<string, Good117> = {};
for (const [id, name, region, tier, building, time, inputs] of _C.g) {
  const gathered = gatheredSet.has(id);
  GOODS_117[id] = {
    id,
    name,
    region,
    regionNames: Object.keys(REGIONS_117)
      .map(Number)
      .filter((r) => region & r)
      .map((r) => REGIONS_117[r]),
    tier: tier || null,
    tierName: tier ? TIER_LABELS_117[tier] || tier : null,
    building,
    time,
    // Every 117 factory has one output and every amount is 1, so the rate is
    // just the cycle: 60/cycleTime t/min.
    rate: time ? Math.round((60 / time) * 1e6) / 1e6 : 0,
    inputs: inputs ? inputs.split("|").map((g) => ({ good: g, qty: 1 })) : [],
    isFinal: !!tier,
    producers: data.producers[id] || [],
    gathered,
  };
}

/** Lowest category band any tier assigns to a good (basic < ... < luxury). */
export const GOODCAT_117: Record<string, number> = {};
for (const tid in POP_117)
  for (const gid in POP_117[tid].n) {
    const c = POP_117[tid].n[gid][1];
    GOODCAT_117[gid] = Math.min(GOODCAT_117[gid] ?? 9, c);
  }

/** Is this good produced in the given region? */
export function inRegion117(goodId: string, region: number): boolean {
  return !!(GOODS_117[goodId]?.region & region);
}

/** The producer to use for a good in a given region — the chain and the rate
 *  both vary, so callers must pick per region rather than trusting the tuple.
 *  Falls back to the primary when the good isn't made there (it's imported). */
export function producerIn117(goodId: string, region: number): Producer117 | null {
  const g = GOODS_117[goodId];
  if (!g?.producers.length) return null;
  return g.producers.find((p) => p.region & region) ?? g.producers[0];
}

/** Goods a tier needs that its own region cannot make — the import list, and
 *  the natural seed for 117 trade routes. */
export function importsFor117(tierId: string): string[] {
  const t = POP_117[tierId];
  if (!t) return [];
  return Object.keys(t.n).filter((gid) => !inRegion117(gid, t.region));
}

export function tierName117(t: string | null | undefined): string {
  return t ? TIER_LABELS_117[t] || t : "—";
}
