// Anno 117 game data, generated by scripts/extract-117.mjs from
// anno-mods/anno-117-calculator (see data-117.json `source` for the pinned
// commit). Regenerate with `npm run extract:117`; don't hand-edit the JSON.
// The 1800 counterpart is data.ts — this mirrors its shape so the two packs
// read the same way, with the differences called out below.
import raw from "./data-117.json";

/** [id, name, regionMask, tier, building, cycleTime, "input|input"] */
export type GoodTuple117 = [string, string, number, string, string | null, number, string];

/** [tons/min per resident, category band 0..3 (see CAT_LABELS_117), residents
 *  this need adds to every house of the tier that is supplied it].
 *
 *  That third number is 117's answer to 1800's `fh`. A 117 residence has no
 *  fixed capacity: its population is the sum of `pop` over the needs it is
 *  actually served (0..3 residents each), which is why no residents-per-house
 *  constant exists upstream. 39 of the 81 needs are worth 0 — they pay
 *  happiness/money instead, and supplying them grows nothing. Pack 2+. */
export type NeedDef117 = [number, number, number];

/** One way to make a good. A good can have several: the same building in both
 *  regions, a different building per region (Flour: Grain Mill in Latium,
 *  Donkey Mill in Albion), different inputs per region (Leather, Amphorae,
 *  Tiles), or a same-region choice (Coal: Charcoal Burner or Coal Mine). */
export interface Producer117 {
  building: string;
  time: number;
  inputs: string;
  /** Bitmask of the regions this producer exists in. */
  region: number;
  /** Burns FUEL_117.good on top of its inputs. */
  fuel?: boolean;
  /** Takes a Silo module (Sheep Farm, Pig Farm, Horse Breeder). Comes from the
   *  factory's `additionalModule`, NOT from modulesLimit below. */
  silo?: boolean;
  /** Max module SLOTS this building takes — a farm's fields are modules too,
   *  which is why these run to 80/140/180. A Silo occupies slots like any
   *  other module; this is NOT a count of silos. */
  modulesLimit?: number;
  /** Needs this island fertility/deposit to be placeable. */
  fertility?: string | boolean;
}

/** A public-service building or Wonder a residence asks for. */
export interface Service117 {
  id: string;
  lbl: string;
  /** Category band 0..3, same axis as a good's need. */
  cat: number;
  /** Residents it adds to every house of the tier once built. */
  pop: number;
  /** One per island (Forum, Colosseum, Barrow) rather than per settlement. */
  wonder?: boolean;
}

export interface PopTier117 {
  lbl: string;
  /** 1 Latium or 2 Albion — a tier belongs to exactly one region. */
  region: number;
  workforceFactor: number | null;
  workforce: number | null;
  n: Record<string, NeedDef117>;
  /** Public-service buildings and Wonders the tier needs. These grant
   *  population exactly like a good does (a Tavern is +1/house, the Colosseum
   *  +3), so they count toward capacity — but a Wonder is one per island
   *  rather than per settlement, hence the flag. Objects since pack 2. */
  services: Service117[];
}

export interface Good117 {
  id: string;
  name: string;
  /** Bitmask, NOT a single region id like data.ts: 1 Latium, 2 Albion, 3 both. */
  region: number;
  regionNames: string[];
  tier: string | null;
  tierName: string | null;
  /** The primary producer's building — null for a gathered good. */
  building: string | null;
  time: number;
  /** t/min per building at base productivity. 0 for a gathered good. */
  rate: number;
  inputs: { good: string; qty: number }[];
  isFinal: boolean;
  /** Every way to make it, primary first. Empty when gathered. */
  producers: Producer117[];
  /** Comes from an island deposit, not a building (Obsidian). */
  gathered: boolean;
}

interface RawData117 {
  _C: {
    version: string;
    game: string;
    g: GoodTuple117[];
    alts: Record<string, never>;
    POP: Record<string, PopTier117>;
    tierOrder: Record<string, number>;
    tierLabels: Record<string, string>;
    regions: Record<string, string>;
    catLabels: string[];
  };
  producers: Record<string, Producer117[]>;
  gathered: string[];
  fuel: { good: string | null; time: number };
  silo: { feedGood: string | null; feedPerMin: number | null; productivityUpgrade: number | null };
  presets: { name: string; sel: Record<string, [string, number]> }[];
  source: Record<string, string>;
}

const data = raw as unknown as RawData117;
const _C = data._C;

export const VERSION_117 = _C.version;
export const SOURCE_117 = data.source;
export const REGIONS_117: Record<number, string> = Object.fromEntries(
  Object.entries(_C.regions).map(([k, v]) => [Number(k), v])
);
export const TIER_ORDER_117 = _C.tierOrder;
export const TIER_LABELS_117 = _C.tierLabels;
export const POP_117 = _C.POP;
export const CAT_LABELS_117 = _C.catLabels;
export const PRESETS_117 = data.presets;

/** Buildings that burn fuel consume one unit of `good` per `time` seconds, so a
 *  building on a `cycleTime` loop burns cycleTime/time each cycle. */
export const FUEL_117 = data.fuel;
/** The Silo module: eats `feedPerMin` t/min of `feedGood` and raises output. */
export const SILO_117 = data.silo;

const gatheredSet = new Set(data.gathered);

export const GOODS_117: Record<string, Good117> = {};
for (const [id, name, region, tier, building, time, inputs] of _C.g) {
  const gathered = gatheredSet.has(id);
  GOODS_117[id] = {
    id,
    name,
    region,
    regionNames: Object.keys(REGIONS_117)
      .map(Number)
      .filter((r) => region & r)
      .map((r) => REGIONS_117[r]),
    tier: tier || null,
    tierName: tier ? TIER_LABELS_117[tier] || tier : null,
    building,
    time,
    // Every 117 factory has one output and every amount is 1, so the rate is
    // just the cycle: 60/cycleTime t/min.
    rate: time ? Math.round((60 / time) * 1e6) / 1e6 : 0,
    inputs: inputs ? inputs.split("|").map((g) => ({ good: g, qty: 1 })) : [],
    isFinal: !!tier,
    producers: data.producers[id] || [],
    gathered,
  };
}

/** Lowest category band any tier assigns to a good (basic < ... < luxury). */
export const GOODCAT_117: Record<string, number> = {};
for (const tid in POP_117)
  for (const gid in POP_117[tid].n) {
    const c = POP_117[tid].n[gid][1];
    GOODCAT_117[gid] = Math.min(GOODCAT_117[gid] ?? 9, c);
  }

/** Is this good produced in the given region? */
export function inRegion117(goodId: string, region: number): boolean {
  return !!(GOODS_117[goodId]?.region & region);
}

/** The producer to use for a good in a given region — the chain and the rate
 *  both vary, so callers must pick per region rather than trusting the tuple.
 *  Falls back to the primary when the good isn't made there (it's imported). */
export function producerIn117(goodId: string, region: number): Producer117 | null {
  const g = GOODS_117[goodId];
  if (!g?.producers.length) return null;
  return g.producers.find((p) => p.region & region) ?? g.producers[0];
}

/** Goods a tier needs that its own region cannot make — the import list, and
 *  the natural seed for 117 trade routes. */
export function importsFor117(tierId: string): string[] {
  const t = POP_117[tierId];
  if (!t) return [];
  return Object.keys(t.n).filter((gid) => !inRegion117(gid, t.region));
}

export function tierName117(t: string | null | undefined): string {
  return t ? TIER_LABELS_117[t] || t : "—";
}

/** One thing a tier can be supplied, and what it is worth in residents. */
export interface PopSource117 {
  /** Good id, or the service/wonder id. */
  id: string;
  lbl: string;
  kind: "good" | "service" | "wonder";
  /** Category band 0..3. */
  cat: number;
  /** Residents added to every house of the tier. Often 0. */
  pop: number;
}

/** Everything a tier's residence can be served, richest first.
 *
 *  This is 117's replacement for 1800's `fh`: rather than a fixed
 *  residents-per-house, capacity is assembled from these. Callers decide which
 *  bands to count and whether to include wonders (one per island, so they are
 *  kept out of a per-settlement headline). Order is by residents gained, so the
 *  list doubles as "what should I supply next".
 */
export function popSources117(tierId: string): PopSource117[] {
  const t = POP_117[tierId];
  if (!t) return [];
  const out: PopSource117[] = [];
  for (const gid in t.n) {
    const [, cat, pop] = t.n[gid];
    out.push({ id: gid, lbl: GOODS_117[gid]?.name ?? gid, kind: "good", cat, pop });
  }
  for (const s of t.services)
    out.push({ id: s.id, lbl: s.lbl, kind: s.wonder ? "wonder" : "service", cat: s.cat, pop: s.pop });
  // Richest first, then band, then name — a stable order for the goals list.
  return out.sort((a, b) => b.pop - a.pop || a.cat - b.cat || a.lbl.localeCompare(b.lbl));
}

/** Residents per fully-supplied house of a tier, counting needs up to `band`
 *  (0..3). Wonders are excluded unless asked for, since one Colosseum serves an
 *  island rather than each settlement. Returns 0 for an unknown tier. */
export function houseCapacity117(tierId: string, band = 3, withWonders = false): number {
  return popSources117(tierId)
    .filter((s) => s.cat <= band && (withWonders || s.kind !== "wonder"))
    .reduce((n, s) => n + s.pop, 0);
}
